"""Capa de dominio para transformar datos en grafos schema.org."""

from .builders import (
    SCHEMA_BUILDERS,
    append_organization,
    build_bank_account_graph,
    build_blog_posting_graph,
    build_financial_product_graph,
    build_investment_or_deposit_graph,
    build_insurance_agency_graph,
    build_loan_or_credit_graph,
    build_offer_catalog_node,
    build_offer_node,
    build_payment_card_graph,
    build_payment_service_graph,
    build_product_node,
    build_webpage_node,
    deep_merge,
    organization_reference,
    resolve_organization,
)

__all__ = [
    "SCHEMA_BUILDERS",
    "append_organization",
    "build_bank_account_graph",
    "build_blog_posting_graph",
    "build_financial_product_graph",
    "build_investment_or_deposit_graph",
    "build_insurance_agency_graph",
    "build_loan_or_credit_graph",
    "build_offer_catalog_node",
    "build_offer_node",
    "build_payment_card_graph",
    "build_payment_service_graph",
    "build_product_node",
    "build_webpage_node",
    "deep_merge",
    "organization_reference",
    "resolve_organization",
]
